name: Process New Issue

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process Issue and Call API Gateway
        env:
          API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}
        run: |
          
          # Call API Gateway and trigger Lambda
          response=$(curl -X POST "$API_GATEWAY_URL" \
            -H "Accept: */*" \
            -H "Content-Type: application/json" \
            -d "${{ toJSON(github.event) }}")
          
          echo "HTTP Status Code: $response"
          
          if [ "$response" -ne 200 ]; then
            echo "Error: API request failed"
            exit 1
          fi