name: Process New Issue

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process Issue and Call API Gateway
        env:
          API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}
        run: |
          # Prepare GitHub event data as JSON payload
          event_json=$(jq -c . <<< '${{ toJSON(github.event) }}')

          curl -X POST "$API_GATEWAY_URL" \
               -H "Content-Type: application/json" \
               -d "$event_json"
